# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "hashicorp/precise32"
  config.vm.network "private_network", ip: "192.168.33.13"
  config.vm.network "forwarded_port", guest: 7474, host: 7474

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "768"]
     vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
     vb.customize ["modifyvm", :id, "--vtxvpid", "off"]  
  end
  
  # Provisioning script
  config.vm.provision "shell", path: "prov.sh"
  
  # SSH configurations
  config.vm.network :forwarded_port, guest: 22, host: 12917, id: 'ssh'
  config.ssh.username = 'vagrant'
  # config.ssh.password = 'vagrant'
  
end
