# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  # config.vm.box = "hashicorp/precise64"
  config.vm.box = "hashicorp/precise32"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  
  config.vm.provider "virtualbox" do |vb|
     # Don't boot with headless mode
     #vb.gui = true
     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "1024"]
     vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
     vb.customize ["modifyvm", :id, "--vtxvpid", "off"]  
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Provisioning script
  config.vm.provision "shell", path: "prov.sh"
  
  # SSH configurations
  # config.ssh.host = "192.168.32.10"
  config.vm.network :forwarded_port, guest: 22, host: 12914, id: 'ssh'
  # config.ssh.port = 22221
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  
end
